server:
  port: 9002

# 应用名称
spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: http://192.168.111.128:81

# 公开信息
management:
  endpoint:
    web:
      exposure:
        include:'*'